[package]
name = "surfer-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]



[dev-dependencies]
ctor = "1.0.3"
env_logger = "0.11.10"


[dependencies]
glam = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
quick-xml = { version = "0.31", features = ["serde"] }


