import { Effect } from "effect";
import type { BoardModel, BezierCurveData } from "../../../components/pages/board-builder-page.logic";
import type { BoardCurves } from "./board-curves";
import { clientLog } from "../clientLog";
import { getBoardProfileAtZ, getBottomYAt } from "./mesh-generator";

const INCHES_TO_CM = 2.54;

/**
 * Translates Super Shaper 9000 [X, Y, Z] (inches) to Shape3d[X, Y, Z] (cm)
 *
 * SS9000:
 * - X: Width (0 at stringer)
 * - Y: Thickness (0 at center of board, bottom is -T/2)
 * - Z: Length (0 at center, -L/2 at nose, +L/2 at tail)
 *
 * Shape3d:
 * - X: Length (0 at Absolute Tail, +L at Nose)
 * - Y: Width (0 at stringer)
 * - Z: Thickness (0 at bottom bounding box)
 */
export const translateToShape3d = (
  [x, y, z]: [number, number, number],
  boardLengthInches: number,
  boardThicknessInches: number
):[number, number, number] => {
  // 1. X_s3d (Length): Distance from tail. Tail in SS9000 is +L/2.
  const x_s3d = (boardLengthInches / 2 - z) * INCHES_TO_CM;

  // 2. Y_s3d (Width): Maps directly from X_ss9000
  const y_s3d = x * INCHES_TO_CM;

  // 3. Z_s3d (Thickness): Offset so bottom plane (-T/2) is at 0
  const z_s3d = (y + boardThicknessInches / 2) * INCHES_TO_CM;

  // Format to 6 decimal places as requested by .s3dx spec precision
  return[
    Number(x_s3d.toFixed(6)),
    Number(y_s3d.toFixed(6)),
    Number(z_s3d.toFixed(6)),
  ];
};

export interface S3DBezier {
  controlPoints: [number, number, number][];
  tangents1: [number, number, number][]; // Incoming (left) handles
  tangents2: [number, number, number][]; // Outgoing (right) handles
}

const reverseCurve = (curve: BezierCurveData): BezierCurveData => {
  return {
    controlPoints: [...curve.controlPoints].reverse(),
    tangents1: [...curve.tangents2].reverse(),
    tangents2: [...curve.tangents1].reverse()
  };
};

export const translateBezierToShape3d = (
  bezier: BezierCurveData,
  boardLengthInches: number,
  boardThicknessInches: number,
  flattenZ: boolean = false,
  reverse: boolean = true
): S3DBezier => {
  const target = reverse ? reverseCurve(bezier) : bezier;
  
  const mapPoints = (pts: [number, number, number][]) => pts.map(p => {
    const pt = translateToShape3d(p, boardLengthInches, boardThicknessInches);
    if (flattenZ) pt[2] = 0.000000;
    return pt;
  });

  return {
    controlPoints: mapPoints(target.controlPoints),
    tangents1: mapPoints(target.tangents1),
    tangents2: mapPoints(target.tangents2),
  };
};

export const exportS3dx = (
  model: BoardModel,
  curves: BoardCurves
): Effect.Effect<string> =>
  Effect.gen(function* () {
    yield* clientLog(
      "info",
      "[s3dx-exporter] Starting Coordinate Translation Pipeline"
    );

    // Translate the exact Bezier curves to Shape3d World Coordinates
    // Shape3D requires the Outline curve to be strictly 2D at Z=0
    const otlBezier = translateBezierToShape3d(model.outline, model.length, model.thickness, true, true);
    const botBezier = translateBezierToShape3d(model.rockerBottom, model.length, model.thickness, false, true);
    const deckBezier = translateBezierToShape3d(model.rockerTop, model.length, model.thickness, false, true);

    const slicesXml = model.crossSections.map((cs, idx) => {
      // Cross sections are not reversed because they are purely lateral
      const s3dSlice = translateBezierToShape3d(cs, model.length, model.thickness, false, false);
      const centerZ = s3dSlice.controlPoints.length > 0 ? s3dSlice.controlPoints[s3dSlice.controlPoints.length - 1]![2] : 0;
      return serializeCoupleXML(idx, s3dSlice, centerZ);
    }).join("\n");

    yield* clientLog("debug", "[s3dx-exporter] Bezier Curves Translated", {
      outlineAnchors: otlBezier.controlPoints.length,
      bottomAnchors: botBezier.controlPoints.length,
      crossSections: model.crossSections.length
    });
    
    // Generate Fin Box and Leash Plug XML
    const plugsAndFinsXML = generatePlugsAndFinsXML(model, curves);

    // XML Serialization & Metadata Injection
    return `<?xml version="1.0" encoding="iso-8859-1"?>
<Shape3d_design>
	<Board>
		<Version>9</Version>
		<VersionNumber>9.1.1.2</VersionNumber>
		<Name>SuperShaper_${model.length.toFixed(1)}</Name>
		<Author>Super Shaper 9000</Author>
		<Comment>Generated by Loft Engine</Comment>
		<Length>${(model.length * INCHES_TO_CM).toFixed(3)}</Length>
		<Width>${(model.width * INCHES_TO_CM).toFixed(3)}</Width>
		<Thickness>${(model.thickness * INCHES_TO_CM).toFixed(3)}</Thickness>
		<Tail_rocker>0.000</Tail_rocker>
		<Nose_rocker>0.000</Nose_rocker>
		<Volume>${model.volume.toFixed(3)}</Volume>
		<Symmetry>6</Symmetry>
${serializeBezier3d("Otl", "", 1, otlBezier, model.length)}
${serializeBezier3d("StrBot", "Stringer Bot", 2, botBezier, model.length)}
${serializeBezier3d("StrDeck", "Stringer Top", 2, deckBezier, model.length)}
		<Number_of_slices>${model.crossSections.length}</Number_of_slices>
${slicesXml}
${plugsAndFinsXML}
	</Board>
</Shape3d_design>`;
  });

/**
 * Serializes a mapped Bezier curve into Shape3d's proprietary XML format.
 */
const serializeBezier3d = (tag: string, name: string, plan: number, bezier: S3DBezier, boardLengthInches: number): string => {
  const centerLengthCm = (boardLengthInches / 2) * INCHES_TO_CM;
  
  const formatPt = (p:[number, number, number]) => 
    `\t\t\t\t\t\t\t<Point3d>\n\t\t\t\t\t\t\t\t<x>${p[0].toFixed(6)}</x><y>${p[1].toFixed(6)}</y><z>${p[2].toFixed(6)}</z><u>-1.000000</u><color>0</color>\n\t\t\t\t\t\t\t</Point3d>`;
  
  const buildPoly = (pts:[number, number, number][], overridePlan: number = plan, overrideSymmetry: number = tag === "Otl" ? 6 : 0) => 
    `\t\t\t\t\t<Polygone3d>\n\t\t\t\t\t\t<Nb_of_points>${pts.length}</Nb_of_points>\n\t\t\t\t\t\t<Open>1</Open>\n\t\t\t\t\t\t<Symmetry>${overrideSymmetry}</Symmetry>\n\t\t\t\t\t\t<Symmetry_center>\n\t\t\t\t\t\t\t<Point3d>\n\t\t\t\t\t\t\t\t<x>${centerLengthCm.toFixed(6)}</x><y>0.000000</y><z>0.000000</z><u>-1.000000</u><color>0</color>\n\t\t\t\t\t\t\t</Point3d>\n\t\t\t\t\t\t</Symmetry_center>\n\t\t\t\t\t\t<Plan>${overridePlan}</Plan>\n${pts.map(formatPt).join("\n")}\n\t\t\t\t\t</Polygone3d>`;

  const tangM = `\t\t\t\t<Tangents_m>\n${buildPoly(bezier.controlPoints.map(() => [0,0,0] as[number,number,number]), 0, 0)}\n\t\t\t\t</Tangents_m>`;
  
  const getControlType = (i: number, total: number) => {
    // End points are '32', intermediate points are '0'
    if (i === 0 || i === total - 1) return 32;
    return 0;
  };

  const getTangentType = (i: number, total: number, curveType: 'outline' | 'rocker' ) => {
    if (i === 0 || i === total - 1) return 0;
    if (curveType === 'outline') {
      return 2;
    } else {
      return 32;
    }
  };

  const controlTypes = bezier.controlPoints.map((_, i) => 
    `\t\t\t\t<Control_type_point_${i}> ${getControlType(i, bezier.controlPoints.length)} </Control_type_point_${i}>`
  ).join("\n");
  
  const tangentTypes = bezier.controlPoints.map((_, i) => 
    `\t\t\t\t<Tangent_type_point_${i}> ${getTangentType(i, bezier.controlPoints.length, tag === 'Otl' ? 'outline' : 'rocker')} </Tangent_type_point_${i}>`
  ).join("\n");

  return `\t\t<${tag}>
\t\t\t<Bezier3d>
\t\t\t\t<Name>${name}</Name>
\t\t\t\t<Degree>3</Degree>
\t\t\t\t<Open>${tag === "Otl" ? 0 : 1}</Open>
\t\t\t\t<Symmetry>${tag === "Otl" ? 6 : 0}</Symmetry>
\t\t\t\t<Plan>${plan}</Plan>
\t\t\t\t<Control_points>\n${buildPoly(bezier.controlPoints)}\n\t\t\t\t</Control_points>
\t\t\t\t<Tangents_1>\n${buildPoly(bezier.tangents1)}\n\t\t\t\t</Tangents_1>
\t\t\t\t<Tangents_2>\n${buildPoly(bezier.tangents2)}\n\t\t\t\t</Tangents_2>
${tangM}
${controlTypes}
${tangentTypes}
\t\t\t</Bezier3d>
\t\t</${tag}>`;
};

const serializeCoupleXML = (index: number, bezier: S3DBezier, centerZ: number): string => {
  const nbPoints = bezier.controlPoints.length;

  const formatPt = (p:[number, number, number]) => 
    `\t\t\t\t\t\t\t<Point3d>\n\t\t\t\t\t\t\t\t<x>${p[0].toFixed(6)}</x><y>${p[1].toFixed(6)}</y><z>${p[2].toFixed(6)}</z><u>-1.000000</u><color>0</color>\n\t\t\t\t\t\t\t</Point3d>`;
  
  const buildPoly = (pts: [number, number, number][], overridePlan: number = 3, overrideSymmetry: number = 6) => 
    `\t\t\t\t\t<Polygone3d>\n\t\t\t\t\t\t<Nb_of_points>${pts.length}</Nb_of_points>\n\t\t\t\t\t\t<Open>1</Open>\n\t\t\t\t\t\t<Symmetry>${overrideSymmetry}</Symmetry>\n\t\t\t\t\t\t<Symmetry_center>\n\t\t\t\t\t\t\t<Point3d>\n\t\t\t\t\t\t\t\t<x>0.000000</x><y>0.000000</y><z>${centerZ.toFixed(6)}</z><u>-1.000000</u><color>0</color>\n\t\t\t\t\t\t\t</Point3d>\n\t\t\t\t\t\t</Symmetry_center>\n\t\t\t\t\t\t<Plan>${overridePlan}</Plan>\n${pts.map(formatPt).join("\n")}\n\t\t\t\t\t</Polygone3d>`;

  // Tangents_m is always zeroed out in couples
  const emptyPt = `\t\t\t\t\t\t\t<Point3d>\n\t\t\t\t\t\t\t\t<x>0.000000</x><y>0.000000</y><z>0.000000</z><u>-1.000000</u><color>0</color>\n\t\t\t\t\t\t\t</Point3d>`;
  const tangM = `\t\t\t\t\t<Polygone3d>\n\t\t\t\t\t\t<Nb_of_points>${nbPoints}</Nb_of_points>\n\t\t\t\t\t\t<Open>1</Open>\n\t\t\t\t\t\t<Symmetry>0</Symmetry>\n\t\t\t\t\t\t<Plan>0</Plan>\n${Array(nbPoints).fill(emptyPt).join("\n")}\n\t\t\t\t\t</Polygone3d>`;

  const getControlType = (i: number, total: number) => {
    if (i === 0 || i === total - 1) return 224;
    if (total === 5) {
      if (i === 1) return 33;
      if (i === 2) return 98;
      if (i === 3) return 32;
    }
    return 32; // Default for inner points
  };

  const getTangentType = (i: number, total: number) => {
    if (i === 0 || i === total - 1) return 0;
    if (total === 5) {
      if (i === 1) return 0;
      if (i === 2) return 16;
      if (i === 3) return 2;
    }
    return 2; // Default tangent mapping
  };

  const controlTypes = bezier.controlPoints.map((_, i) => 
    `\t\t\t\t<Control_type_point_${i}> ${getControlType(i, nbPoints)} </Control_type_point_${i}>`
  ).join("\n");
  
  const tangentTypes = bezier.controlPoints.map((_, i) => 
    `\t\t\t\t<Tangent_type_point_${i}> ${getTangentType(i, nbPoints)} </Tangent_type_point_${i}>`
  ).join("\n");

  return `\t\t<Couples_${index}>
\t\t\t\t<Dessus>1</Dessus>
\t\t\t\t<Dessous>1</Dessous>
\t\t\t\t<Displayed>0</Displayed>
\t\t\t<Bezier3d>
\t\t\t\t<Name>cpl</Name>
\t\t\t\t<Degree>3</Degree>
\t\t\t\t<Open>0</Open>
\t\t\t\t<Symmetry>6</Symmetry>
\t\t\t\t<Plan>3</Plan>
\t\t\t\t<Control_points>\n${buildPoly(bezier.controlPoints)}\n\t\t\t\t</Control_points>
\t\t\t\t<Tangents_1>\n${buildPoly(bezier.tangents1)}\n\t\t\t\t</Tangents_1>
\t\t\t\t<Tangents_2>\n${buildPoly(bezier.tangents2)}\n\t\t\t\t</Tangents_2>
\t\t\t\t<Tangents_m>\n${tangM}\n\t\t\t\t</Tangents_m>
${controlTypes}
${tangentTypes}
\t\t\t</Bezier3d>
\t\t</Couples_${index}>`;
};

// ====================================================================
// FIN BOX & LEASH PLUG GENERATION LOGIC
// ====================================================================

const generatePlugsAndFinsXML = (model: BoardModel, curves: BoardCurves): string => {
  const boxConfigs: { name: string; zFromTail: number; xFromCenter: number; isCenter: boolean; isSide: boolean; isPlug: boolean }[] =[];

  // 1. Fins
  if (model.finSetup === 'thruster') {
    boxConfigs.push({ name: "Fin sides", zFromTail: model.frontFinZ, xFromCenter: model.frontFinX, isCenter: false, isSide: true, isPlug: false });
    boxConfigs.push({ name: "Fin center", zFromTail: model.rearFinZ, xFromCenter: 0, isCenter: true, isSide: false, isPlug: false });
  } else if (model.finSetup === 'quad') {
    boxConfigs.push({ name: "Fin sides", zFromTail: model.frontFinZ, xFromCenter: model.frontFinX, isCenter: false, isSide: true, isPlug: false });
    boxConfigs.push({ name: "Fin sides", zFromTail: model.rearFinZ, xFromCenter: model.rearFinX, isCenter: false, isSide: true, isPlug: false });
  } else if (model.finSetup === 'twin') {
    boxConfigs.push({ name: "Fin sides", zFromTail: model.frontFinZ, xFromCenter: model.frontFinX, isCenter: false, isSide: true, isPlug: false });
  }

  // 2. Leash Plug (Standard placement: 3.5 inches from tail on the stringer)
  boxConfigs.push({ name: "Leash 1", zFromTail: 3.5, xFromCenter: 0, isCenter: false, isSide: false, isPlug: true });

  if (boxConfigs.length === 0) {
    return "<Nb_Boxes>0</Nb_Boxes>";
  }

  const boxesXML = boxConfigs.map((box, i) => {
    // 1. Calculate position in our coordinate system
    const z_ss = model.length / 2 - box.zFromTail;
    const profile = getBoardProfileAtZ(model, curves, z_ss);
    const x_ss = box.isCenter || box.isPlug ? 0 : profile.halfWidth - box.xFromCenter;
    
    let y_ss = 0;
    if (box.isPlug) {
      // Leash plug sits flush on the deck
      y_ss = profile.topY;
    } else {
      // Fins sit flush on the bottom contours
      y_ss = getBottomYAt(model, curves, x_ss, z_ss);
    }

    // 2. Translate to S3D coordinates for the <Ref. point>
    const refPointS3D = translateToShape3d([x_ss, y_ss, z_ss], model.length, model.thickness);
    
    // Helper to format 3D points exactly like Shape3D expects
    const formatPt = (pt: [number, number, number]) => 
      `\t\t\t<Point3d>\n\t\t\t\t<x>${pt[0].toFixed(6)}</x><y>${pt[1].toFixed(6)}</y><z>${pt[2].toFixed(6)}</z><u>-1.000000</u><color>0</color>\n\t\t\t</Point3d>`;

    // 3. Static values from reference for standard elements
    const boxLengthCm = box.isPlug ? 2.7 : 15.0;
    const boxWidthCm = box.isPlug ? 2.7 : 3.2;
    const boxHeightCm = box.isPlug ? 1.6 : 1.55;
    const diameter = box.isPlug ? 2.7 : 3.2;
    const c1c2 = box.isPlug ? 0.0 : 11.8;
    const reflexion = box.isPlug ? 0 : 20;
    
    const face = box.isPlug ? 0 : 1; // 0 = Deck, 1 = Bottom
    const style = box.isPlug ? 4 : 3; // 4 = Plug, 3 = Fin Box
    const toeInRad = box.isSide ? (model.toeAngle * Math.PI / 180).toFixed(4) : "0.0000";
    
    const ptConvergence = box.isSide ? `\n\t\t\t<PtConvergence>250.000000</PtConvergence>` : "";

    return `\t\t<Box_${i}>
\t\t<Box>
\t\t\t<Name>${box.name}</Name>
\t\t\t<Length>${boxLengthCm.toFixed(3)}</Length>
\t\t\t<Width>${boxWidthCm.toFixed(3)}</Width>
\t\t\t<Height>${boxHeightCm.toFixed(3)}</Height>
\t\t\t<Diameter>${diameter.toFixed(3)}</Diameter>
\t\t\t<C1C2>${c1c2.toFixed(3)}</C1C2>
\t\t\t<Color>0</Color>
\t\t\t<Reflexion_coef>${reflexion}</Reflexion_coef>
\t\t\t<Even>${box.isSide ? 1 : 0}</Even>
\t\t\t<Central>${box.isCenter ? 1 : 0}</Central>
\t\t\t<SymNoseTail>0</SymNoseTail>
\t\t\t<IFixedToBt>-1</IFixedToBt>
\t\t\t<DistFixedTo>0.000</DistFixedTo>
\t\t\t<AFixedTo>0.000</AFixedTo>
\t\t\t<FixedTail>${box.isPlug ? 0 : 1}</FixedTail>
\t\t\t<FixedNose>0</FixedNose>
\t\t\t<FixedCenter>0</FixedCenter>
\t\t\t<FixedRail>${box.isSide ? 1 : 0}</FixedRail>
\t\t\t<Face>${face}</Face>
\t\t\t<Style>${style}</Style>
\t\t\t<Ref. point>
${formatPt(refPointS3D)}</Ref. point>
\t\t\t<PointRef>
${formatPt(refPointS3D)}</PointRef>
\t\t\t<PointRefDx>${box.isCenter || box.isPlug ? '0.000' : '-1.500'}</PointRefDx>
\t\t\t<PointRefDy>${box.isSide ? '0.320' : '0.000'}</PointRefDy>
\t\t\t<PointCenter>
${formatPt(refPointS3D)}</PointCenter>
\t\t\t<FinLength>10.160</FinLength>${ptConvergence}
\t\t\t<AngleOz>${toeInRad}</AngleOz>
\t\t\t<DisplayD3D>1</DisplayD3D>
\t\t\t<MappingD3D>1</MappingD3D>
\t\t\t<ImageMappedD3D>White</ImageMappedD3D>
\t\t\t<CutCNC>1</CutCNC>
\t\t\t<DpLibelle>
\t\t\t<Point2d>
\t\t\t\t<x>0.000000</x><y>0.000000</y><color>337156096</color>
\t\t\t</Point2d></DpLibelle>
\t\t</Box>
\t\t</Box_${i}>`;
  }).join('\n');

  return `<Nb_Boxes>${exportBoxes.length}</Nb_Boxes>\n${boxesXML}`;
};
